name = "syuink-signal"
main = "src/index.ts"
compatibility_date = "2023-12-01"

# Define the Durable Object binding
[[durable_objects.bindings]]
name = "SIGNAL_ROOM"
class_name = "SignalRoom"

# Configure migration for the Durable Object
[[migrations]]
tag = "v1" # Unique version tag
new_classes = ["SignalRoom"]

[[d1_databases]]
binding = "DB"
database_name = "syuink-db"
database_id = "local-db-id"
